///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
//
// tdm.c
// The code will be automatically generated by TDM.
//
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

#include "tdm.h"
//#include <stdio.h>
#include <stdlib.h>

///////////////////////////////////////////////////////////////////////////////
// Static variables
///////////////////////////////////////////////////////////////////////////////

static const int TDMNumberOfAtomicModels = 2;							// Number of atomic models in the code
static tdmAtomicModel * TDMAtomicModels = 0;							// Memory block for storing all the atomic models
static tdmCommon * TDMStateVariableBlock = 0;							// Memory block for storing state variables of all the atomic models
static const int TDMSizeOfStateVariableBlock = sizeof (tdmCommon) * 2;	// Size of TDMStateVariableBlock in bytes
static tdmTime * TDMNextEventTimeBlock = 0;

///////////////////////////////////////////////////////////////////////////////
// Atomic Model A
// 0: SEND
// 1: WAUT
// 2: IDLE

void TDM_A_Initialization (tdmAtomicModel * Model)
{
	Model -> StateVariables [0] . Integer = 0;
	printf ("0 initialized.\n");
}

void TDM_A_ExternalTransition (tdmAtomicModel * Model, tdmTime ElapsedTime, tdmEvent ExternalEvent)
{
	switch (Model -> StateVariables [0] . Integer)
	{
		default:
			Model -> StateVariables [0] . Integer = 2;
	}
}

void TDM_A_InternalTransition (tdmAtomicModel * Model)
{
	switch (Model -> StateVariables [0] . Integer)
	{
		case 0:
			Model -> StateVariables [0] . Integer = 1;
			break;

		default:
			Model -> StateVariables [0] . Integer = 2;
			break;
	}
}

tdmEvent TDM_A_Output (tdmAtomicModel * Model)
{
	return (tdmEvent) {. Integer = 0};
}

void TDM_A_TimeAdvance (tdmAtomicModel * Model)
{
	switch (Model -> StateVariables [0] . Integer)
	{
		case 0:
			* Model -> NextTimeEvent = 0.0;
			break;

		case 1:
			* Model -> NextTimeEvent = 60.0;
			break;

		default:
			* Model -> NextTimeEvent = tdmTimeInfinite;
	}
}

///////////////////////////////////////////////////////////////////////////////
// Atomic Model B
// 0: REPLY
// 1: IDLE

void TDM_B_Initialization (tdmAtomicModel * Model)
{
	Model -> StateVariables = TDMStateVariableBlock + 1;
	Model -> StateVariables [0] . Integer = 1;
	printf ("1 initialized.\n");
}

void TDM_B_ExternalTransition (tdmAtomicModel * Model, tdmTime ElapsedTime, tdmEvent ExternalEvent)
{
	switch (Model -> StateVariables [0] . Integer)
	{
		default:
			Model -> StateVariables [0] . Integer = 0;
	}
}

void TDM_B_InternalTransition (tdmAtomicModel * Model)
{
	switch (Model -> StateVariables [0] . Integer)
	{
		default:
			Model -> StateVariables [0] . Integer = 1;
			break;
	}
}

tdmEvent TDM_B_Output (tdmAtomicModel * Model)
{
	return (tdmEvent) {. Integer = 0};
}

void TDM_B_TimeAdvance (tdmAtomicModel * Model)
{
	switch (Model -> StateVariables [0] . Integer)
	{
		case 0:
			* Model -> NextTimeEvent = rand () % 100;
			break;

		default:
			* Model -> NextTimeEvent = tdmTimeInfinite;
	}
}

bool TDMInitializeModels (void)
{
	TDMAtomicModels = malloc (sizeof (tdmAtomicModel) * TDMNumberOfAtomicModels);
	TDMStateVariableBlock = malloc (sizeof (tdmCommon) * TDMSizeOfStateVariableBlock);
	TDMNextEventTimeBlock = malloc (sizeof (tdmTime) * TDMNumberOfAtomicModels);

	TDMAtomicModels [0] . StateVariables = TDMStateVariableBlock;
	TDMAtomicModels [0] . InitializationFunction = TDM_A_Initialization;
	TDMAtomicModels [0] . ExternalTransitionFunction = TDM_A_ExternalTransition;
	TDMAtomicModels [0] . InternalTransitionFunction = TDM_A_InternalTransition;
	TDMAtomicModels [0] . OutputFunction = TDM_A_Output;
	TDMAtomicModels [0] . TimeAdvanceFunction = TDM_A_TimeAdvance;
	TDMAtomicModels [0] . NextTimeEvent = TDMNextEventTimeBlock;

	TDMAtomicModels [1] . StateVariables = TDMStateVariableBlock + 1;
	TDMAtomicModels [1] . InitializationFunction = TDM_B_Initialization;
	TDMAtomicModels [1] . ExternalTransitionFunction = TDM_B_ExternalTransition;
	TDMAtomicModels [1] . InternalTransitionFunction = TDM_B_InternalTransition;
	TDMAtomicModels [1] . OutputFunction = TDM_B_Output;
	TDMAtomicModels [1] . TimeAdvanceFunction = TDM_B_TimeAdvance;
	TDMAtomicModels [1] . NextTimeEvent = TDMNextEventTimeBlock + 1;

	return true;
}

///////////////////////////////////////////////////////////////////////////////
// Model-independent functions
///////////////////////////////////////////////////////////////////////////////

bool TDMFinalizeModels (void)
{
	if (TDMNextEventTimeBlock)
	{
		free (TDMNextEventTimeBlock);
	}

	if (TDMStateVariableBlock)
	{
		free (TDMStateVariableBlock);
	}

	if (TDMAtomicModels)
	{
		free (TDMAtomicModels);
	}

	return true;
}

int TDMGetNumberOfAtomicModels (void)
{
	return TDMNumberOfAtomicModels;
}

tdmAtomicModel * TDMGetAtomicModels (void)
{
	return TDMAtomicModels;
}

tdmTime * TDMGetNextEventTimeBlock (void)
{
	return TDMNextEventTimeBlock;
}

///////////////////////////////////////////////////////////////////////////////